steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/auralix-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/auralix-api:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/auralix-api:$COMMIT_SHA'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auralix-api'
      - '--image=gcr.io/$PROJECT_ID/auralix-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,WEBSERVER_PORT=8080,WEBSERVER_HOST=0.0.0.0,WEBSERVER_NAME=Auralix API,WEBSERVER_VERSION=1.0.0,LOG_LEVEL=info,RATE_LIMIT_WINDOW_MS=900000,RATE_LIMIT_MAX_REQUESTS=50'
      - '--set-secrets=JWT_SECRET=JWT_SECRET:latest,SESSION_SECRET=SESSION_SECRET:latest,SECRET_KEY=SECRET_KEY:latest,MONGODB_URL=MONGODB_URL:latest,MONGODB_DB_NAME=MONGODB_DB_NAME:latest,SPOTIFY_CLIENT_ID=SPOTIFY_CLIENT_ID:latest,SPOTIFY_CLIENT_SECRET=SPOTIFY_CLIENT_SECRET:latest'

images:
  - 'gcr.io/$PROJECT_ID/auralix-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/auralix-api:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  timeout: '1200s'
